### ISSUE TITLE
Add to fdroid

### ISSUE THREAD

**Issue by Thewisem** [hashemi-hossein/memory-guardian#19]
Fdroid is a free and open source app source whoch is made for open aource enthusiasts it would be a great if you could upload this there

**Comment by hashemi-hossein** [comment]
Thanks @Thewisem for your suggestion.
I filled the proposal more than a year ago but it has not been added yet. I follow it up to make it happen

**Comment by IzzySoft** [comment]
It is however [available in the IzzyOnDroid repo](https://apt.izzysoft.de/packages/ara.memoryguardian) for over a year now. @hashemi-hossein be welcome to [pick a badge](https://gitlab.com/IzzyOnDroid/repo/#if-my-app-is-available-here-do-you-have-a-badge-i-can-use-to-link-to-it) to link there e.g. from your Readme.

As for your ping to me from the RFP: Sorry, I'm currently [not active at F-Droid](https://gitlab.com/fdroid/admin/-/issues/447).

@Thewisem you can add the IzzyOnDroid repo to your F-Droid client. Depending on which one you use, it might even be pre-configured already (Neo Store and Droid-ify have it, for example). Otherwise you can find some short instructions at the top of the [repo-browser here](https://apt.izzysoft.de/fdroid/). IzzyOnDroid is the largest 3rd-party F-Droid repo, serving about 1.200 apps currently – many which are not available at F-Droid (yet), like Memory Guardian, or stuck there with their updates. If you have concerns about security or the like, take a look at [Ramping up security: additional APK checks are in place with the IzzyOnDroid repo](https://android.izzysoft.de/articles/named/iod-scan-apkchecks), you should be covered well with it. More exciting news are expected to "go live" this week…

**Comment by hashemi-hossein** [comment]
Thank you for your response @IzzySoft

**Comment by IzzySoft** [comment]
> Thank you for your response

Gladly, @hashemi-hossein! I see your app reached F-Droid today, congrats! However, the [IoD Badge](https://gitlab.com/IzzyOnDroid/repo/#if-my-app-is-available-here-do-you-have-a-badge-i-can-use-to-link-to-it) seems still missing from your Readme, you only added the F-Droid one. I hope this does not mean you want your app removed from IzzyOnDroid? Would be a pity, as it's one of the apps with [Reproducible Builds](https://android.izzysoft.de/articles/named/iod-rbs-mirrors-clients) and gives you faster updates (<24h of your having the release ready) plus [extra security checks](https://android.izzysoft.de/articles/named/iod-scan-apkchecks) :wink:

**Comment by IzzySoft** [comment]
Thanks! And yes, you've picked the correct one. The other is just a "partly integration" with the app listings. Still had no time to find a proper integration – ideally using the original place in a "frame" or something…
